class_name Minigame
extends Node3D
## Base class of every minigame scene (`game/minigames/<id>/<id>.tscn`).
## Scene layout: a `Spawns` Node3D with 8 Marker3D children (their +Z faces where the
## player should look), plus the minigame's own ground, light and fixed camera.
## Flow (driven by Session): Stage spawns frozen players and sets `players` ->
## `_setup(players)` on every peer -> countdown -> players unfrozen, `_start()` on every
## peer -> `_host_tick(delta)` on the host each physics frame -> host calls `finish(ranking)`.
## Orchestrator-owned base class: override the virtuals, do not edit this file.

## Slots, best first. Emitted once, on the host.
signal finished(ranking: Array[int])

@export var title: String = ""
## One line shown on the title card.
@export var rule_text: String = ""
## Seconds. Shown by the round UI; the minigame itself calls finish() when it runs out
## (from `_host_tick`). 0 means no time limit.
@export var time_limit: float = 60.0

## Every player in this round, set by Stage before `_setup`.
var players: Array[Player] = []
## Slots in the order `knock_out` removed them (first out first).
var knocked_out: Array[int] = []

var _finished: bool = false


## Transforms of the Marker3D children of $Spawns, in child order.
func get_spawn_points() -> Array[Transform3D]:
	var points: Array[Transform3D] = []
	var spawns := get_node_or_null(^"Spawns")
	if spawns == null:
		return points
	for child in spawns.get_children():
		var m := child as Marker3D
		if m:
			points.append(m.global_transform if m.is_inside_tree() else _local_to_self(m))
	return points


## Virtual. Every peer; players are frozen. Change component tuning here.
func _setup(_players: Array[Player]) -> void:
	pass


## Virtual. Every peer, after the countdown.
func _start() -> void:
	pass


## Virtual. Host only, every physics frame while playing.
func _host_tick(_delta: float) -> void:
	pass


## Host only. Ends the round with `ranking` (slots, best first). Later calls are ignored.
func finish(ranking: Array[int]) -> void:
	if _finished:
		return
	_finished = true
	finished.emit(ranking)


## True once finish() has been called.
func is_finished() -> bool:
	return _finished


## Host only. Eliminates `player` and records the order; when one player (or none) is
## left, finishes with the survivor first, then the knocked-out in reverse order.
func knock_out(player: Player) -> void:
	if _finished or player == null or not player.alive:
		return
	knocked_out.append(player.slot)
	player.eliminate(&"knocked_out")
	var alive_slots: Array[int] = []
	for p in players:
		if p.alive:
			alive_slots.append(p.slot)
	if alive_slots.size() <= 1:
		var ranking: Array[int] = alive_slots.duplicate()
		for i in range(knocked_out.size() - 1, -1, -1):
			ranking.append(knocked_out[i])
		finish(ranking)


## Where a bot should want to be. Default: a random spawn point.
func get_bot_goal(_player: Player) -> Vector3:
	var points := get_spawn_points()
	if points.is_empty():
		return global_position
	return points[randi() % points.size()].origin


## Bots avoid positions where this returns false. Default: everywhere is safe.
func is_safe(_pos: Vector3) -> bool:
	return true


func _local_to_self(m: Node3D) -> Transform3D:
	var xform := m.transform
	var n := m.get_parent() as Node3D
	while n and n != self:
		xform = n.transform * xform
		n = n.get_parent() as Node3D
	return xform
