class_name Minigame
extends Node3D
## Base class of every minigame scene (`game/minigames/<id>/<id>.tscn`).
## Scene layout: a `Spawns` Node3D with 8 Marker3D children (their +Z faces where the
## player should look), plus the minigame's own ground, light and fixed camera.
## Flow (driven by Session): Stage spawns frozen players and sets `players` ->
## `_setup(players)` on every peer -> countdown -> players unfrozen, `_start()` on every
## peer -> `_host_tick(delta)` on the host each physics frame -> host calls `finish(ranking)`
## (optionally with a `grace`: Session keeps the round on screen, everyone frozen, that long
## before the results, e.g. Paint Splat's "final splat").
## Ties: a ranking entry is a slot or an Array of slots (a tied group sharing one place).
## Teams and roles (optional, host decides, replicated): `assign_teams`, `finish_teams`,
## `set_role_text`; see docs/contract.md "Teams, ties and roles".
## Game modes (optional): a subclass may declare `var mutator_blocklist: Array[StringName] = [...]`
## (mutators this minigame never gets, e.g. `[&"slippery"]`; Session reads the script default
## before the round, so set it in the declaration, not in `_setup`). It is NOT declared here, so
## declaring it does not clash. `active_mutator` / `_mutator_changed` tell the minigame which
## mutator the round has (players' tuning is already scaled by the size component).
## Orchestrator-owned base class: override the virtuals, do not edit this file.

## Slots, best first (tied groups flattened in order; `finish_groups` keeps the groups).
## Emitted once, on the host.
signal finished(ranking: Array[int])
## Bots: raised by `request_bot_rethink`. Bot brains listen and re-ask `get_bot_goal`.
signal bot_rethink_requested(slot: int)
## The team assignment reached this peer (every peer, after `assign_teams` on the host).
signal teams_changed
## A role line reached this peer (every peer, after `set_role_text` on the host).
signal role_changed(slot: int, text: String)

## Team colours by team index: colour-blind-safe (Okabe-Ito) and unlike the player colours.
const TEAM_COLORS: Array[Color] = [Color("#e69f00"), Color("#56b4e9"), Color("#009e73"), Color("#cc79a7")]
const TEAM_NAMES: Array[String] = ["ORANGE", "BLUE", "GREEN", "PINK"]
const MAX_TEAMS := 4

@export var title: String = ""
## One line shown on the title card.
@export var rule_text: String = ""
## Seconds. Shown by the round UI; the minigame itself calls finish() when it runs out
## (from `_host_tick`). 0 means no time limit.
@export var time_limit: float = 60.0

## Every player in this round, set by Stage before `_setup`.
var players: Array[Player] = []
## Slots in the order `knock_out` removed them (first out first).
var knocked_out: Array[int] = []

## Seconds of presentation the host asked for in finish() (Session reads it). Host only.
var finish_grace: float = 0.0
## The ranking finish() was given, normalised: an Array of `Array[int]` groups, best first
## (a group of 2+ is a tie). Session reads it. Host only.
var finish_groups: Array = []
## slot -> team index (0-based), every peer; empty without teams (see assign_teams).
var teams: Dictionary[int, int] = {}
## Teams of the last assign_teams (0 = no teams).
var team_count: int = 0
## slot -> role line shown to that player ("You are the SEEKER"), every peer (set_role_text).
var roles: Dictionary[int, String] = {}
## Every peer: this round's mutator id (&"" = none), set by Session with the INTRO before
## `_setup` (so `_setup` may read it) and cleared at RESULTS.
var active_mutator: StringName = &""

var _finished: bool = false


## Transforms of the Marker3D children of $Spawns, in child order.
func get_spawn_points() -> Array[Transform3D]:
	var points: Array[Transform3D] = []
	var spawns := get_node_or_null(^"Spawns")
	if spawns == null:
		return points
	for child in spawns.get_children():
		var m := child as Marker3D
		if m:
			points.append(m.global_transform if m.is_inside_tree() else _local_to_self(m))
	return points


## Virtual. Every peer; players are frozen. Change component tuning here.
func _setup(_players: Array[Player]) -> void:
	pass


## Virtual. Every peer, after the countdown.
func _start() -> void:
	pass


## Virtual. Every peer: the round's mutator was set (`id`) or taken off (&""). Player tuning is
## already handled; react only if the minigame has its own physics (a ball, falling props).
func _mutator_changed(_id: StringName) -> void:
	pass


## Virtual. Host only, every physics frame while playing.
func _host_tick(_delta: float) -> void:
	pass


## Host only. Ends the round with `ranking`, best first. Later calls are ignored.
## Each entry is a slot (int) or an Array of slots: a tied group that shares the place (every
## member scores that place's points), e.g. `finish([3, [1, 2], 0])`.
## `grace` > 0: Session holds PLAYING with every player frozen on every peer for that many
## seconds (a closing moment: the last splat, a winner pose) before RESULTS; `finished` still
## fires now and the ranking is already decided.
func finish(ranking: Array, grace: float = 0.0) -> void:
	if _finished:
		return
	_finished = true
	finish_grace = maxf(0.0, grace)
	finish_groups = normalize_ranking(ranking)
	finished.emit(flatten_groups(finish_groups))


## Host only. Ends the round ranking whole teams, best first (`team_order`: team indices):
## every team is one tied group. Teams missing from `team_order` follow in index order, then
## players without a team as one last group.
func finish_teams(team_order: Array[int], grace: float = 0.0) -> void:
	var order: Array[int] = []
	for t in team_order:
		if t >= 0 and not order.has(t):
			order.append(t)
	for t in team_count:
		if not order.has(t):
			order.append(t)
	var ranking: Array = []
	for t in order:
		ranking.append(team_slots(t))
	var rest: Array[int] = []
	for p in players:
		if is_instance_valid(p) and team_of(p.slot) < 0:
			rest.append(p.slot)
	rest.sort()
	ranking.append(rest)
	finish(ranking, grace)


## True once finish() has been called.
func is_finished() -> bool:
	return _finished


## Host only. Eliminates `player` (with `reason`, default `knocked_out`) and records the
## order; when one player (or none) is left, finishes with the survivor first, then the
## knocked-out in reverse order.
func knock_out(player: Player, reason: StringName = &"") -> void:
	if _finished or player == null or not player.alive:
		return
	if player.is_extra:
		player.eliminate(reason if reason != &"" else &"knocked_out")  # NPC extras are never ranked
		return
	knocked_out.append(player.slot)
	player.eliminate(reason if reason != &"" else &"knocked_out")
	var alive_slots: Array[int] = []
	for p in players:
		if p.alive:
			alive_slots.append(p.slot)
	if alive_slots.size() <= 1:
		var ranking: Array[int] = alive_slots.duplicate()
		for i in range(knocked_out.size() - 1, -1, -1):
			ranking.append(knocked_out[i])
		finish(ranking)


## Where a bot should want to be. Default: a random spawn point.
func get_bot_goal(_player: Player) -> Vector3:
	var points := get_spawn_points()
	if points.is_empty():
		return global_position
	return points[randi() % points.size()].origin


## Optional, host. Tells bots that what `get_bot_goal` answers has changed (a coin was
## taken, the bomb changed hands), so they re-ask after their own short reaction delay
## instead of at their next routine refresh. `slot` -1 = every bot.
func request_bot_rethink(slot: int = -1) -> void:
	bot_rethink_requested.emit(slot)


## Bots avoid positions where this returns false. Default: everywhere is safe.
func is_safe(_pos: Vector3) -> bool:
	return true


# --- Ties ----------------------------------------------------------------------------------

## A ranking whose entries are slots or Arrays of slots -> the canonical form: an Array of
## `Array[int]` groups, best first. Repeated slots keep their first place; empty groups go.
static func normalize_ranking(ranking: Array) -> Array:
	var groups: Array = []
	var seen: Dictionary = {}
	for entry: Variant in ranking:
		var members: Array = []
		if entry is Array or entry is PackedInt32Array or entry is PackedInt64Array:
			members = Array(entry)
		else:
			members.append(entry)
		var group: Array[int] = []
		for m: Variant in members:
			if not (m is int or m is float):
				continue
			var slot := int(m)
			if seen.has(slot):
				continue
			seen[slot] = true
			group.append(slot)
		if not group.is_empty():
			groups.append(group)
	return groups


## Groups -> the flat order (groups concatenated, best first).
static func flatten_groups(groups: Array) -> Array[int]:
	var flat: Array[int] = []
	for g: Variant in groups:
		if g is Array:
			for s: Variant in g:
				flat.append(int(s))
		else:
			flat.append(int(g))
	return flat


## 1-based place of `slot` in `groups` (1 + the players in better groups); 0 if absent.
static func group_place(groups: Array, slot: int) -> int:
	var before := 0
	for g: Variant in groups:
		var members: Array = g if g is Array else [g]
		if members.has(slot):
			return before + 1
		before += members.size()
	return 0


# --- Teams ---------------------------------------------------------------------------------

## Host only (ignored elsewhere). Splits the living players into `count` teams (2..MAX_TEAMS)
## at random, sizes differing by at most one, and sends the result to every peer
## (`teams`, the players' team rings, the round UI; `teams_changed` fires on each peer).
## Call it in `_setup` (the intro card then shows each player's team) or later.
func assign_teams(count: int = 2) -> void:
	if not _is_host():
		return
	var slots: Array[int] = []
	for p in players:
		if is_instance_valid(p) and p.alive:
			slots.append(p.slot)
	var split := split_teams(slots, count)
	_rpc_set_teams.rpc(split.keys(), split.values(), clampi(count, 2, MAX_TEAMS))


## `slots` shuffled and dealt into `count` (2..MAX_TEAMS) teams: slot -> team. Sizes differ by
## at most one; which teams get the odd players is random.
static func split_teams(slots: Array[int], count: int) -> Dictionary[int, int]:
	count = clampi(count, 2, MAX_TEAMS)
	var order := slots.duplicate()
	order.shuffle()
	var offset := randi() % count
	var out: Dictionary[int, int] = {}
	for i in order.size():
		out[order[i]] = (offset + i) % count
	return out


## True while this round has teams.
func has_teams() -> bool:
	return team_count > 0 and not teams.is_empty()


## Team index of `slot`, -1 if none.
func team_of(slot: int) -> int:
	return teams.get(slot, -1)


## Slots on `team`, ascending.
func team_slots(team: int) -> Array[int]:
	var out: Array[int] = []
	for s: int in teams:
		if teams[s] == team:
			out.append(s)
	out.sort()
	return out


## Colour of `team` (white for none).
static func team_color(team: int) -> Color:
	return TEAM_COLORS[team] if team >= 0 and team < TEAM_COLORS.size() else Color.WHITE


## Display name of `team` ("ORANGE", "BLUE", ...; "" for none).
static func team_name(team: int) -> String:
	return TEAM_NAMES[team] if team >= 0 and team < TEAM_NAMES.size() else ""


## True when `a` and `b` are on the same team (false without teams). Bot brains must not
## shove allies.
func is_ally(a: Player, b: Player) -> bool:
	if a == null or b == null:
		return false
	var ta := team_of(a.slot)
	return ta >= 0 and ta == team_of(b.slot)


@rpc("authority", "call_local", "reliable")
func _rpc_set_teams(slots: Array, team_ids: Array, count: int) -> void:
	teams.clear()
	for i in mini(slots.size(), team_ids.size()):
		teams[int(slots[i])] = int(team_ids[i])
	team_count = count if not teams.is_empty() else 0
	_apply_team_markers(false)
	teams_changed.emit()


## Shows (or with `clear`, removes) every player's team ring.
func _apply_team_markers(clear: bool) -> void:
	for p in players:
		if not is_instance_valid(p):
			continue
		var marker := p.get_component(&"team") as TeamComponent
		if marker:
			var t := -1 if clear else team_of(p.slot)
			marker.set_team(t, team_color(t))


# --- Roles ---------------------------------------------------------------------------------

## Host only (ignored elsewhere). The line player `slot` sees on the intro card and as a
## banner at round start, e.g. "You are the SEEKER" ("" clears it). Sent to every peer.
func set_role_text(slot: int, text: String) -> void:
	if _is_host():
		_rpc_set_role.rpc(slot, text)


## The role line of `slot` ("" if none).
func role_of(slot: int) -> String:
	return roles.get(slot, "")


@rpc("authority", "call_local", "reliable")
func _rpc_set_role(slot: int, text: String) -> void:
	if text == "":
		roles.erase(slot)
	else:
		roles[slot] = text
	role_changed.emit(slot, text)


func _is_host() -> bool:
	return is_inside_tree() and multiplayer.is_server()


func _notification(what: int) -> void:
	# Teams live on this minigame: when it leaves (round over, stage cleared) the rings go too.
	if what == NOTIFICATION_EXIT_TREE and not teams.is_empty():
		_apply_team_markers(true)


func _local_to_self(m: Node3D) -> Transform3D:
	var xform := m.transform
	var n := m.get_parent() as Node3D
	while n and n != self:
		xform = n.transform * xform
		n = n.get_parent() as Node3D
	return xform
