extends Node
## Autoload `Sfx`: sound effects. Owner: audio.
##
## `play(sound, at)` plays a one-shot: positional (pooled AudioStreamPlayer3D) when `at` is
## given, otherwise non-positional (pooled AudioStreamPlayer). Every sound has an entry in
## `sounds` (volume, random pitch spread, polyphony limit, minimum gap between starts, bus,
## variant files), so 8 players landing at once give a few voices, not a wall of noise.
## Loops: `play_loop(sound, at) -> id`, `move_loop(id, at)`, `stop_loop(id)`.
## Buses `Sfx` and `Ui` are created from code when the project has no such bus;
## `set_volume(bus, linear)` sets a bus (or `Master`) volume. `attach_ui(root)` gives every
## button under `root` focus/press sounds. Works headless: all bookkeeping runs, only the
## actual play() is skipped (see `_audible`).
##
## Files: res://audio/sfx/<file>.wav, generated by art/scripts/audio/gen_sfx.py.

## Emitted whenever a voice actually starts (after throttling). Test seam.
signal played(sound: StringName, at: Vector3)

const SFX_DIR := "res://audio/sfx/"
const BUS_SFX := &"Sfx"
const BUS_UI := &"Ui"
## Pool sizes: the hard ceiling of simultaneous one-shots.
const POOL_3D := 24
const POOL_2D := 12

## Per-sound settings. Missing keys fall back to SOUND_DEFAULTS.
##   vol: volume in dB; pitch: random pitch spread (+-fraction); max: voices of this sound at
##   once (the oldest is restarted beyond that); gap: ms between two starts of this sound
##   (closer starts are dropped); bus; files: variant files picked at random (default [name]).
const SOUND_DEFAULTS := {"vol": 0.0, "pitch": 0.05, "max": 4, "gap": 30, "bus": BUS_SFX}

## Unit size (m) of positional sounds: full volume within it, then 1/distance falloff.
@export var unit_size: float = 10.0
@export var max_distance: float = 90.0
@export var panning_strength: float = 0.6

## Tunable at runtime: `Sfx.sounds[&"jump"]["vol"] = -3.0`.
var sounds: Dictionary[StringName, Dictionary] = {
	&"jump": {"vol": -4.0, "pitch": 0.08, "max": 4},
	&"land_soft": {"vol": -5.0, "pitch": 0.08, "max": 4},
	&"land_hard": {"vol": -2.0, "pitch": 0.06, "max": 3},
	&"step": {"vol": -8.0, "pitch": 0.1, "max": 4, "gap": 35, "files": [&"step_a", &"step_b", &"step_c"]},
	&"step_a": {"vol": -8.0, "pitch": 0.1, "max": 3},
	&"step_b": {"vol": -8.0, "pitch": 0.1, "max": 3},
	&"step_c": {"vol": -8.0, "pitch": 0.1, "max": 3},
	&"shove_whoosh": {"vol": -3.0, "pitch": 0.1, "max": 4},
	&"hit_bonk": {"vol": -1.0, "pitch": 0.1, "max": 4, "gap": 40},
	&"stun_wobble": {"vol": -5.0, "pitch": 0.06, "max": 3, "gap": 80},
	&"eliminated_pop": {"vol": -1.0, "pitch": 0.08, "max": 4},
	&"respawn": {"vol": -4.0, "pitch": 0.03, "max": 3},
	&"coin": {"vol": -4.0, "pitch": 0.04, "max": 4, "gap": 40},
	&"coin_big": {"vol": -2.0, "pitch": 0.02, "max": 2},
	&"bomb_tick": {"vol": -3.0, "pitch": 0.0, "max": 2},
	&"bomb_fuse_loop": {"vol": -8.0, "pitch": 0.0, "max": 2},
	&"explosion": {"vol": 0.0, "pitch": 0.08, "max": 3, "gap": 60},
	&"platform_crack": {"vol": -3.0, "pitch": 0.1, "max": 4, "gap": 40},
	&"platform_fall": {"vol": -6.0, "pitch": 0.08, "max": 3, "gap": 60},
	&"lava_sizzle": {"vol": -5.0, "pitch": 0.1, "max": 3, "gap": 60},
	&"countdown_beep": {"vol": -4.0, "pitch": 0.0, "max": 1, "gap": 0, "bus": BUS_UI},
	&"countdown_go": {"vol": -3.0, "pitch": 0.0, "max": 1, "gap": 0, "bus": BUS_UI},
	&"round_win_jingle": {"vol": -3.0, "pitch": 0.0, "max": 1, "bus": BUS_UI},
	&"round_end": {"vol": -3.0, "pitch": 0.0, "max": 1, "bus": BUS_UI},
	&"podium_fanfare": {"vol": -2.0, "pitch": 0.0, "max": 1, "bus": BUS_UI},
	&"ui_move": {"vol": -6.0, "pitch": 0.03, "max": 2, "gap": 40, "bus": BUS_UI},
	&"ui_click": {"vol": -4.0, "pitch": 0.02, "max": 2, "gap": 40, "bus": BUS_UI},
	&"ui_back": {"vol": -4.0, "pitch": 0.02, "max": 2, "gap": 40, "bus": BUS_UI},
	&"join_chime": {"vol": -4.0, "pitch": 0.0, "max": 2, "gap": 150, "bus": BUS_UI},
	&"leave_chime": {"vol": -5.0, "pitch": 0.0, "max": 2, "gap": 150, "bus": BUS_UI},
	&"piano_c": {"vol": -4.0, "pitch": 0.0, "max": 3, "gap": 20},
	&"piano_d": {"vol": -4.0, "pitch": 0.0, "max": 3, "gap": 20},
	&"piano_e": {"vol": -4.0, "pitch": 0.0, "max": 3, "gap": 20},
	&"piano_f": {"vol": -4.0, "pitch": 0.0, "max": 3, "gap": 20},
	&"piano_g": {"vol": -4.0, "pitch": 0.0, "max": 3, "gap": 20},
	&"piano_a": {"vol": -4.0, "pitch": 0.0, "max": 3, "gap": 20},
	&"piano_b": {"vol": -4.0, "pitch": 0.0, "max": 3, "gap": 20},
	&"portal_hum_loop": {"vol": -10.0, "pitch": 0.0, "max": 4},
}

var _streams: Dictionary[StringName, AudioStream] = {}
var _pool_3d: Array[AudioStreamPlayer3D] = []
var _pool_2d: Array[AudioStreamPlayer] = []
## player instance id -> {"sound": StringName, "start": msec, "end": msec}
var _voices: Dictionary[int, Dictionary] = {}
var _last_start: Dictionary[StringName, int] = {}
var _warned: Dictionary[StringName, bool] = {}
var _loops: Dictionary[int, Node] = {}
var _next_loop_id: int = 1
var _ui_roots: Array[WeakRef] = []
var _rng := RandomNumberGenerator.new()
## False when headless: everything (voices, limits, signals) runs except the actual play(),
## because a stream still playing at quit is reported as a leaked resource.
var _audible: bool = true
## Pre-warm (audible only): files still to load, a few per frame, starting PREWARM_DELAY s
## after startup, so a sound's first play does not read its .wav from disk (~1-2 ms each,
## several at once when a round's first knock-out or unmasking sets off a burst).
const PREWARM_DELAY := 0.6
const PREWARM_PER_FRAME := 3
var _prewarm: Array[StringName] = []
var _prewarm_wait: float = PREWARM_DELAY


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_rng.randomize()
	_audible = DisplayServer.get_name() != "headless"
	_ensure_bus(BUS_SFX)
	_ensure_bus(BUS_UI)
	for i in POOL_3D:
		var p := AudioStreamPlayer3D.new()
		p.name = "Voice3D_%d" % i
		p.bus = BUS_SFX
		p.unit_size = unit_size
		p.max_distance = max_distance
		p.panning_strength = panning_strength
		p.doppler_tracking = AudioStreamPlayer3D.DOPPLER_TRACKING_DISABLED
		add_child(p)
		_pool_3d.append(p)
	for i in POOL_2D:
		var p := AudioStreamPlayer.new()
		p.name = "Voice2D_%d" % i
		p.bus = BUS_SFX
		add_child(p)
		_pool_2d.append(p)
	if _audible:
		for sound: StringName in sounds:
			for f: Variant in sounds[sound].get("files", [sound]):
				if not _prewarm.has(StringName(f)):
					_prewarm.append(StringName(f))
	set_process(not _prewarm.is_empty())


## Pre-warm: loads PREWARM_PER_FRAME sound files per frame into the stream cache.
func _process(delta: float) -> void:
	_prewarm_wait -= delta
	if _prewarm_wait > 0.0:
		return
	for i in PREWARM_PER_FRAME:
		if _prewarm.is_empty():
			break
		_load_stream(_prewarm.pop_front())
	if _prewarm.is_empty():
		set_process(false)


## Release every playing stream on quit, so no stream is still held by the audio server
## when the engine checks for leaked resources.
func _exit_tree() -> void:
	stop_all()
	for p: Node in _pool_3d + _pool_2d:
		p.set(&"stream", null)
	_streams.clear()


# --- One-shots ----------------------------------------------------------------------------

## Plays `sound`; positional at `at`, or non-positional when `at` is Vector3.INF.
## `volume_db` is added to the sound's own volume; `pitch` multiplies its random pitch.
func play(sound: StringName, at: Vector3 = Vector3.INF, volume_db: float = 0.0, pitch: float = 1.0) -> void:
	var cfg := _config(sound)
	if cfg.is_empty():
		return
	var stream := _pick_stream(sound, cfg)
	if stream == null:
		return
	if _is_looping(stream):
		_warn_once(StringName("loop:" + sound), "Sfx.play: '%s' loops, use play_loop()" % sound)
		return
	var now := Time.get_ticks_msec()
	var gap: int = cfg["gap"]
	if gap > 0 and _last_start.has(sound) and now - _last_start[sound] < gap:
		return
	var positional := at != Vector3.INF
	var player := _claim_voice(sound, int(cfg["max"]), positional)
	if player == null:
		return
	var pitch_scale := maxf(0.05, pitch * (1.0 + _rng.randf_range(-1.0, 1.0) * float(cfg["pitch"])))
	var vol := float(cfg["vol"]) + volume_db
	var bus: StringName = cfg["bus"]
	if positional:
		var p3 := player as AudioStreamPlayer3D
		p3.global_position = at
		p3.volume_db = vol
	else:
		(player as AudioStreamPlayer).volume_db = vol
	player.set(&"stream", stream)
	player.set(&"pitch_scale", pitch_scale)
	player.set(&"bus", bus)
	if _audible:
		player.call(&"play")
	_last_start[sound] = now
	_voices[player.get_instance_id()] = {
		"sound": sound, "start": now,
		"end": now + int(ceilf(stream.get_length() / pitch_scale * 1000.0)) + 1,
	}
	played.emit(sound, at)


## Stops every one-shot voice and every loop (leaving a match, returning to the menu).
func stop_all() -> void:
	for p: Node in _pool_3d + _pool_2d:
		p.call(&"stop")
	_voices.clear()
	_last_start.clear()
	for id: int in _loops.keys():
		var loop: Node = _loops[id]
		if is_instance_valid(loop):
			loop.queue_free()
	_loops.clear()


## Voices of `sound` still sounding (by their length; independent of the audio driver).
func voice_count(sound: StringName) -> int:
	var now := Time.get_ticks_msec()
	var n := 0
	for id: int in _voices:
		var v := _voices[id]
		if v["sound"] == sound and int(v["end"]) > now:
			n += 1
	return n


## True if `sound` has a table entry and at least one file.
func has_sound(sound: StringName) -> bool:
	return sounds.has(sound) and _pick_stream(sound, _config(sound, false)) != null


func sound_names() -> Array[StringName]:
	var out: Array[StringName] = []
	out.assign(sounds.keys())
	return out


# --- Loops ---------------------------------------------------------------------------------

## Starts a looping sound (files named *_loop loop by their import settings); positional at
## `at`, or non-positional for Vector3.INF. Returns an id for move_loop/stop_loop, -1 if unknown.
func play_loop(sound: StringName, at: Vector3 = Vector3.INF) -> int:
	var cfg := _config(sound)
	if cfg.is_empty():
		return -1
	var stream := _pick_stream(sound, cfg)
	if stream == null:
		return -1
	var player: Node
	if at != Vector3.INF:
		var p3 := AudioStreamPlayer3D.new()
		p3.unit_size = unit_size
		p3.max_distance = max_distance
		p3.panning_strength = panning_strength
		p3.volume_db = float(cfg["vol"])
		p3.position = at
		player = p3
	else:
		var p2 := AudioStreamPlayer.new()
		p2.volume_db = float(cfg["vol"])
		player = p2
	player.name = "Loop_%d" % _next_loop_id
	player.set(&"stream", stream)
	player.set(&"bus", cfg["bus"])
	add_child(player)
	if _audible:
		player.call(&"play")
	var id := _next_loop_id
	_next_loop_id += 1
	_loops[id] = player
	played.emit(sound, at)
	return id


## Moves a positional loop (a fuse on a bomb being passed around).
func move_loop(id: int, at: Vector3) -> void:
	var p := _loops.get(id) as AudioStreamPlayer3D
	if p and is_instance_valid(p):
		p.global_position = at


## Stops a loop with a short fade. Unknown or already stopped ids are ignored.
func stop_loop(id: int) -> void:
	var p: Node = _loops.get(id)
	_loops.erase(id)
	if p == null or not is_instance_valid(p):
		return
	var tween := p.create_tween()
	tween.tween_property(p, ^"volume_db", -60.0, 0.12)
	tween.tween_callback(p.queue_free)


func is_loop_playing(id: int) -> bool:
	return _loops.has(id) and is_instance_valid(_loops[id])


# --- Volume ----------------------------------------------------------------------------------

## Sets a bus volume from a linear 0..1 slider value (0 mutes). Buses: Master, Sfx, Ui.
func set_volume(bus: StringName, linear: float) -> void:
	var idx := AudioServer.get_bus_index(bus)
	if idx < 0:
		_warn_once(StringName("bus:" + bus), "Sfx.set_volume: no audio bus '%s'" % bus)
		return
	linear = clampf(linear, 0.0, 1.0)
	AudioServer.set_bus_volume_db(idx, linear_to_db(maxf(linear, 0.0001)))
	AudioServer.set_bus_mute(idx, linear <= 0.0)


## Linear 0..1 volume of a bus (0 when muted or missing).
func get_volume(bus: StringName) -> float:
	var idx := AudioServer.get_bus_index(bus)
	if idx < 0 or AudioServer.is_bus_mute(idx):
		return 0.0
	return clampf(db_to_linear(AudioServer.get_bus_volume_db(idx)), 0.0, 1.0)


# --- UI ----------------------------------------------------------------------------------------

## Gives every BaseButton under `root` (now and added later) sounds: focus/hover -> ui_move,
## press -> ui_click, or ui_back for buttons named/labelled back/close/cancel/quit.
## Override per button with meta `sfx_press` (StringName; &"" for silence).
func attach_ui(root: Control) -> void:
	if root == null:
		return
	for ref in _ui_roots:
		if ref.get_ref() == root:
			return
	_ui_roots.append(weakref(root))
	_hook_buttons(root)
	if not get_tree().node_added.is_connected(_on_node_added):
		get_tree().node_added.connect(_on_node_added)


func _hook_buttons(node: Node) -> void:
	if node is BaseButton:
		_hook_button(node as BaseButton)
	for child in node.get_children():
		_hook_buttons(child)


func _hook_button(button: BaseButton) -> void:
	if button.has_meta(&"_sfx_hooked"):
		return
	button.set_meta(&"_sfx_hooked", true)
	button.focus_entered.connect(_ui_hover.bind(button))
	button.mouse_entered.connect(_ui_hover.bind(button))
	button.pressed.connect(_ui_press.bind(button))


func _ui_hover(button: BaseButton) -> void:
	if is_instance_valid(button) and not button.disabled and button.is_visible_in_tree():
		play(&"ui_move")


func _ui_press(button: BaseButton) -> void:
	if not is_instance_valid(button):
		return
	if button.has_meta(&"sfx_press"):
		var custom: StringName = StringName(button.get_meta(&"sfx_press"))
		if custom != &"":
			play(custom)
		return
	var label := String(button.name).to_lower()
	if button is Button:
		label += " " + (button as Button).text.to_lower()
	for word in ["back", "close", "cancel", "quit", "leave"]:
		if label.contains(word):
			play(&"ui_back")
			return
	play(&"ui_click")


func _on_node_added(node: Node) -> void:
	if not node is BaseButton:
		return
	var alive: Array[WeakRef] = []
	for ref in _ui_roots:
		var root := ref.get_ref() as Node
		if root == null:
			continue
		alive.append(ref)
		if root.is_ancestor_of(node):
			_hook_button(node as BaseButton)
	_ui_roots = alive


# --- Internals ---------------------------------------------------------------------------------

func _config(sound: StringName, warn: bool = true) -> Dictionary:
	if not sounds.has(sound):
		if warn:
			_warn_once(sound, "Sfx: unknown sound '%s'" % sound)
		return {}
	var cfg := SOUND_DEFAULTS.duplicate()
	cfg.merge(sounds[sound], true)
	return cfg


func _pick_stream(sound: StringName, cfg: Dictionary) -> AudioStream:
	var files: Array = cfg.get("files", [sound])
	if files.is_empty():
		return null
	var file := StringName(files[_rng.randi_range(0, files.size() - 1)])
	_load_stream(file)
	var stream: AudioStream = _streams[file]
	if stream == null:
		_warn_once(StringName("file:" + file), "Sfx: missing sound file '%s'" % file)
	return stream


## Loads `file` into the stream cache (null when the file is missing), once.
func _load_stream(file: StringName) -> void:
	if _streams.has(file):
		return
	var path := SFX_DIR + String(file) + ".wav"
	var loaded := load(path) as AudioStream if ResourceLoader.exists(path) else null
	# Keep a path-less copy: Godot 4.7 leaks a stream that is still playing when the game
	# quits; a cached (path) resource turns that into an "ERROR: resources still in use"
	# line at exit, a copy only into a harmless leak warning.
	_streams[file] = loaded.duplicate() as AudioStream if loaded else null


## A free player for `sound`: restarts the oldest voice of `sound` when it has `max_voices`
## sounding, else a free pool player, else the oldest voice in the pool.
func _claim_voice(sound: StringName, max_voices: int, positional: bool) -> Node:
	var pool: Array = _pool_3d if positional else _pool_2d
	var now := Time.get_ticks_msec()
	var oldest_same: Node = null
	var oldest_same_t := 1 << 62
	var same := 0
	var free_player: Node = null
	var oldest_any: Node = null
	var oldest_any_t := 1 << 62
	for p: Node in pool:
		var v: Dictionary = _voices.get(p.get_instance_id(), {})
		if v.is_empty() or int(v["end"]) <= now:
			if free_player == null:
				free_player = p
			continue
		var start := int(v["start"])
		if v["sound"] == sound:
			same += 1
			if start < oldest_same_t:
				oldest_same_t = start
				oldest_same = p
		if start < oldest_any_t:
			oldest_any_t = start
			oldest_any = p
	var chosen: Node
	if max_voices > 0 and same >= max_voices:
		chosen = oldest_same
	elif free_player:
		chosen = free_player
	else:
		chosen = oldest_any
	if chosen:
		chosen.call(&"stop")
	return chosen


func _is_looping(stream: AudioStream) -> bool:
	var wav := stream as AudioStreamWAV
	return wav != null and wav.loop_mode != AudioStreamWAV.LOOP_DISABLED


func _ensure_bus(bus: StringName) -> void:
	if AudioServer.get_bus_index(bus) >= 0:
		return
	AudioServer.add_bus()
	var idx := AudioServer.bus_count - 1
	AudioServer.set_bus_name(idx, bus)
	AudioServer.set_bus_send(idx, &"Master")


func _warn_once(key: StringName, message: String) -> void:
	if _warned.has(key):
		return
	_warned[key] = true
	push_warning(message)
